server:
  port: 8080

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 20
      queue_capacity: 100
      name:
        prefix: 'aaa'

shiro:
  ws:
    server:
      enable: true
      url: '/onebotSocket'